# Generated by Django 4.1 on 2022-09-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogging", "0002_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(model_name="category", name="posts",),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="categories", to="blogging.category"
            ),
        ),
    ]
